# Generated by Django 5.0.5 on 2025-05-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0002_immobilier_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immobilier',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
