# Generated by Django 5.0.5 on 2025-05-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0003_alter_immobilier_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='immobilier',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
