# Generated by Django 5.0.5 on 2025-05-23 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0004_immobilier_disponible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('immobilier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='immobilier.immobilier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'immobilier')},
            },
        ),
        migrations.AddField(
            model_name='immobilier',
            name='reserved_by',
            field=models.ManyToManyField(blank=True, related_name='reservations', through='immobilier.Reservation', to=settings.AUTH_USER_MODEL),
        ),
    ]
